### ISSUE TITLE
polars/datatypes.py - NotImplementedError: Conversion of polars data type Categorical to Python type not implemented (Tutorial 1 data)

### ISSUE THREAD

**Issue by samuelruizperez** [hitaandrea/MGcount#5]
Hello again!

I installed `MGcount` and the `subread` package (`featureCounts`) with `pip3` through `conda 22.9.0 (Python 3.7)`:

```
conda create --name env1 python=3.7 subread

conda activate env1

/path/to/anaconda3/envs/env1/bin/pip3 install git+https://github.com/hitaandrea/MGcount.git
```
Then, I followed tutorial "T1 - Prepare inputs and execute" in [MGcount's user guide](https://filedn.com/lTnUWxFTA93JTyX3Hvbdn2h/mgcount/UserGuide.html):

```
mkdir mgcount_tutorial
cd mgcount_tutorial

wget https://filedn.com/lTnUWxFTA93JTyX3Hvbdn2h/mgcount/tutorial_bamfiles.zip
unzip tutorial_bamfiles.zip -d input_bamfiles

printf "$PWD/%s\n" input_bamfiles/* > input_bamfilenames.txt

wget https://filedn.com/lTnUWxFTA93JTyX3Hvbdn2h/mgcount/integrated_annotations_gtf.zip
unzip integrated_annotations_gtf.zip -d annotations_gtf
```

However, when I ran `MGcount` "as a `python3` module" I got an error:
```
/path/to/anaconda3/envs/env1/bin/mgcount \
--n_cores 2 \
--bam_infiles input_bamfilenames.txt \
--gtf annotations_gtf/Homo_sapiens.GRCh38.custom.gtf \
--featureCounts_path /path/to/anaconda3/envs/env1/bin/featureCounts \
--outdir outputs
```
Output (log):

```
--------------------------------------------------------
Assigning alignments to features (1/3)
--------------------------------------------------------
small assignation round for: Human_Brain_total_100ng_2_subsample
long_exon assignation round for: Human_Brain_total_100ng_2_subsample
long_intron assignation round for: Human_Brain_total_100ng_2_subsample
--------------------------------------------------------
Extracting multi-loci groups (2/3)
--------------------------------------------------------
```
Output (error):

```
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'transcript_id', 'transcript_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'transcript_support_level', 'exon_number', 'exon_id', 'exon_version', 'protein_id', 'protein_version', 'ccds_id']

Traceback (most recent call last):
  File "/path/to/anaconda3/envs/env1/bin/mgcount", line 8, in <module>
    sys.exit(main())
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/mgcount/__main__.py", line 269, in main
    th_low, th_high, seed) 
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/mgcount/multigraph.py", line 38, in MG
    gtf[[cround['attr'], cround['btype']]][gtf['feature']==cround['feat']],
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/polars/internals/series/series.py", line 452, in __eq__
    return self._comp(other, "eq")
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/polars/internals/series/series.py", line 444, in _comp
    other = maybe_cast(other, self.dtype, self.time_unit)
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/polars/datatypes.py", line 759, in maybe_cast
    py_type = dtype_to_py_type(dtype)
  File "/path/to/anaconda3/envs/env1/lib/python3.7/site-packages/polars/datatypes.py", line 644, in dtype_to_py_type
    ) from None
NotImplementedError: Conversion of polars data type Categorical to Python type not implemented.

Traceback (most recent call last):
  File "/path/to/anaconda3/envs/env1/lib/python3.7/weakref.py", line 648, in _exitfunc
    f()
  File "/path/to/anaconda3/envs/env1/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/path/to/anaconda3/envs/env1/lib/python3.7/tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "/path/to/anaconda3/envs/env1/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/path/to/anaconda3/envs/env1/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/outputs/.mg_1114_gc_'
```

I tried the same thing now under a `Python 3.11` `conda` environment and got similar errors:

Output (log):
```
--------------------------------------------------------
Assigning alignments to features (1/3)
--------------------------------------------------------
--------------------------------------------------------
Extracting multi-loci groups (2/3)
--------------------------------------------------------
```
Output (error):
```
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version', 'transcript_id', 'transcript_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'havana_transcript', 'havana_transcript_version', 'tag', 'transcript_support_level', 'exon_number', 'exon_id', 'exon_version', 'ccds_id', 'protein_id', 'protein_version']

Traceback (most recent call last):
  File "/path/to/anaconda3/envs/env2/bin/mgcount", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/mgcount/__main__.py", line 268, in main
    ml = mg.MG(infiles, outdir, tmppath, gtf, crounds, btype_crounds, n_cores,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/mgcount/multigraph.py", line 38, in MG
    gtf[[cround['attr'], cround['btype']]][gtf['feature']==cround['feat']],
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/polars/internals/series/series.py", line 452, in __eq__
    return self._comp(other, "eq")
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/polars/internals/series/series.py", line 444, in _comp
    other = maybe_cast(other, self.dtype, self.time_unit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/polars/datatypes.py", line 749, in maybe_cast
    py_type = dtype_to_py_type(dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda3/envs/env2/lib/python3.11/site-packages/polars/datatypes.py", line 632, in dtype_to_py_type
    raise NotImplementedError(
NotImplementedError: Conversion of polars data type Categorical to Python type not implemented.
```
However, using `MGcount` as a binary executable program and following the tutorial (same parameters as before) worked fine:

```
wget https://github.com/hitaandrea/MGcount/releases/download/v1.0.2/MGcount
chmod +x MGcount
```

```
MGcount \
--n_cores 2 \
--bam_infiles input_bamfilenames.txt \
--gtf annotations_gtf/Homo_sapiens.GRCh38.custom.gtf \
--featureCounts_path /path/to/anaconda3/envs/env1/bin/featureCounts \
--outdir outputs
```

Output (log):

```
--------------------------------------------------------
Assigning alignments to features (1/3)
--------------------------------------------------------
small assignation round for: Human_Brain_total_100ng_2_subsample
long_exon assignation round for: Human_Brain_total_100ng_2_subsample
long_intron assignation round for: Human_Brain_total_100ng_2_subsample
--------------------------------------------------------
Extracting multi-loci groups (2/3)
--------------------------------------------------------
Building small multi-mappers graph
Detecting small communities from multi-mappers graph
   --> snRNA multi-loci groups successfully extracted.
   --> misc_RNA multi-loci groups successfully extracted.
   --> scaRNA multi-loci groups successfully extracted.
   --> snoRNA multi-loci groups successfully extracted.
   --> rRNA_pseudogene multi-loci groups successfully extracted.
   --> rRNA multi-loci groups successfully extracted.
   --> ribozyme multi-loci groups successfully extracted.
   --> Mt_tRNA multi-loci groups successfully extracted.
   --> Mt_rRNA multi-loci groups successfully extracted.
   --> piRNA multi-loci groups successfully extracted.
   --> tRNA multi-loci groups successfully extracted.
   --> miRNA multi-loci groups successfully extracted.
Building long_exon multi-mappers graph
   --> Multi-mappers adjacency matrix successfully extracted from 987284 reads and 1120022 alignments!
Detecting long_exon communities from multi-mappers graph
   --> long multi-loci groups successfully extracted.
--------------------------------------------------------
Computing expression matrix (3/3)
--------------------------------------------------------
Human_Brain_total_100ng_1_subsample
Human_Brain_total_100ng_2_subsample

......
Voilà.
Olé!
```

Could this be an error with my versions of `Python`, `conda` or other packages when running `MGcount` as a module?

Thank you for your help,
Samuel

------------------------------
**Session details:**

```
Platform: x86_64-conda-linux-gnu (64-bit) - conda 22.9.0
Running under: Ubuntu 18.04.6 LTS

Packages in environment at /path/to/anaconda3/envs/env1/:

Name                      Version                   Build    Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.10.11           h06a4308_0  
certifi                   2022.12.7        py37h06a4308_0  
gtfparse                  2.0.1                    pypi_0    pypi
igraph                    0.10.3                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libzlib                   1.2.13               h166bdaf_4    conda-forge
mgcount                   1.0.2                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
numpy                     1.21.6                   pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0  
pandas                    1.3.5                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
polars                    0.15.15                  pypi_0    pypi
pysam                     0.20.0                   pypi_0    pypi
python                    3.7.15               h7a1cb2a_1  
python-dateutil           2.8.2                    pypi_0    pypi
python-igraph             0.10.3                   pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
readline                  8.2                  h5eee18b_0  
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.40.1               h5082296_0  
subread                   2.0.3                h7132678_0    bioconda
texttable                 1.6.7                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
typing-extensions         4.4.0                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.8                h5eee18b_0  
zlib                      1.2.13               h166bdaf_4    conda-forge

```

**Comment by hitaandrea** [comment]
Hi Samuel, 

Thank you very much for pointing to this! 

After looking into it, I could reproduce your error after uninstalling mgcount+deppendencies and reinstalling mgcount via pip. There is a conflict with the latest version of the gtfparse python module. I just made a new MGcount release (v1.1.0) with a few recent optimizations we made on the software (now, there is an optional argument for sparse-matrix formatting). In this release, I also updated the pip installer specifications to install the compatible gtfparse module accordingly. 

Now, you should not encounter this error if you re-install mgcount via pip (pip uninstall mgcount; pip install git+https://github.com/hitaandrea/MGcount.git) and then run it as a python module. Otherwise, please, let me know!

Andrea

**Comment by samuelruizperez** [comment]
Hi, Andrea,

Thank you! That was very quick and helpful. 🙂

Samuel
